# Simple Continuous-Angle Walk

In [1]:
import numpy as np

def simulate_continuous_walk(n_particles=100, n_steps=1000, step_size=1.0, seed=None):
    rng = np.random.default_rng(seed)
    # angles: shape (n_steps, n_particles)
    theta = rng.uniform(0, 2*np.pi, size=(n_steps, n_particles))
    # steps shape (n_steps, n_particles, 2)
    steps = np.stack((np.cos(theta), np.sin(theta)), axis=-1) * step_size
    # positions: cumsum over time -> (n_steps, n_particles, 2)
    positions = np.cumsum(steps, axis=0)
    # prepend origin (optional) -> shape (n_steps+1, n_particles, 2)
    origins = np.zeros((1, n_particles, 2))
    positions = np.vstack((origins, positions))
    return positions  # positions[t, p] -> (x,y) at time t


In [6]:
print(simulate_continuous_walk())

[[[  0.           0.        ]
  [  0.           0.        ]
  [  0.           0.        ]
  ...
  [  0.           0.        ]
  [  0.           0.        ]
  [  0.           0.        ]]

 [[  0.45421062  -0.89089433]
  [ -0.25496358   0.96695066]
  [ -0.59886916  -0.80084689]
  ...
  [  0.76951346  -0.6386306 ]
  [  0.99074943  -0.13570393]
  [ -0.95674553   0.2909261 ]]

 [[ -0.53119141  -1.06113781]
  [  0.60934334   0.4639859 ]
  [  0.31903787  -0.40405136]
  ...
  [  0.42464319  -1.57728096]
  [  1.76592643  -0.76744804]
  [ -0.91175164  -0.70806117]]

 ...

 [[ 47.65547381 -25.44031915]
  [-21.3439966  -22.7391785 ]
  [  5.74741174  21.3230366 ]
  ...
  [-10.14434424   3.65185768]
  [ 19.61657913   8.58339077]
  [  8.75156972 -19.69805772]]

 [[ 48.64444581 -25.58842172]
  [-21.75272272 -23.65183559]
  [  4.79698747  21.63399273]
  ...
  [-11.05971104   4.05447862]
  [ 18.93994911   9.31971394]
  [  8.98031817 -20.67154328]]

 [[ 48.031907   -24.7979812 ]
  [-22.09041374 -22.7105

# Simple Lattice Random Walk

In [3]:
def simulate_lattice_walk(n_particles=100, n_steps=1000, seed=None):
    rng = np.random.default_rng(seed)
    # choices: 0=right,1=left,2=up,3=down
    choices = rng.integers(0, 4, size=(n_steps, n_particles))
    dx = np.where(choices==0, 1, np.where(choices==1, -1, 0))
    dy = np.where(choices==2, 1, np.where(choices==3, -1, 0))
    steps = np.stack((dx, dy), axis=-1)
    positions = np.cumsum(steps, axis=0)
    positions = np.vstack((np.zeros((1, n_particles, 2)), positions))
    return positions


In [5]:
print(simulate_lattice_walk())

[[[  0.   0.]
  [  0.   0.]
  [  0.   0.]
  ...
  [  0.   0.]
  [  0.   0.]
  [  0.   0.]]

 [[  0.   1.]
  [ -1.   0.]
  [  1.   0.]
  ...
  [  1.   0.]
  [  0.  -1.]
  [ -1.   0.]]

 [[  0.   0.]
  [ -1.  -1.]
  [  2.   0.]
  ...
  [  1.   1.]
  [ -1.  -1.]
  [ -1.  -1.]]

 ...

 [[-56.  32.]
  [ 48. -28.]
  [ 32.  -2.]
  ...
  [-22. -26.]
  [  0.  24.]
  [  3.  -5.]]

 [[-56.  31.]
  [ 48. -27.]
  [ 32.  -3.]
  ...
  [-23. -26.]
  [  1.  24.]
  [  3.  -6.]]

 [[-56.  30.]
  [ 48. -28.]
  [ 31.  -3.]
  ...
  [-23. -25.]
  [  0.  24.]
  [  3.  -5.]]]
